version: '3.5'

services:

  nginx:
    image: nginx:latest
    build:
      context: docker
      dockerfile: ./nginx/Dockerfile
    container_name: foody_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - laravel
    networks:
      - laravel

  laravel:
    image: laravel:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: foody-laravel
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.6
    container_name: foody_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=foody
    ports:
      - "33061:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    name: laravel
